server:
  port: 8082

spring:
  application:
    name: auth-service
  datasource:
    username: telusmikolaj
    password: admin
    url: jdbc:postgresql://localhost:5432/auth-service
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/coders-platform-realm
logging:
  level:
    org:
      springframework:
        security: DEBUG
        oauth2: DEBUG
      keycloak: DEBUG
