server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    username: telusmikolaj
    password: admin
    url: jdbc:postgresql://localhost:5432/userservice
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: none
    show-sql: true
  rabbitmq:
    addresses: localhost:5672
    username:  admin
    password:  admin

rabbitmq:
  queue:
    registration: user_registration_queue
  exchanges:
    internal: internal.exchange
  routing-keys:
    internal-registration: internal.notification.routing-key


